
### 매장 등록
POST http://localhost:9091/manager/store
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqbEhWc3JwZ2RxeW5RRUhVRkxtZ3lXdjVpako1M0tlb0dNZTVoa2lPc2RBPSIsImp0aSI6IlJucE8xSHd6NXo4WmhtWTZOUUphOVE9PSIsInJvbGVzIjoiTUFOQUdFUiIsImlhdCI6MTY4NTQ0NDIzMiwiZXhwIjoxNjg1NTMwNjMyfQ.06nL2Yz0ouMxryRmF4v3Sa737ejClDAC_AhnJiPO_sk

{
  "location": "서울시 강서구",
  "name": "피씨방",
  "registrationNumber": "811-04-10602",
  "storeInfo": "피씨방입니다.",
  "price": "2000"
}

### 매장 수정
PUT http://localhost:9091/manager/store
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqbEhWc3JwZ2RxeW5RRUhVRkxtZ3lXdjVpako1M0tlb0dNZTVoa2lPc2RBPSIsImp0aSI6IlJucE8xSHd6NXo4WmhtWTZOUUphOVE9PSIsInJvbGVzIjoiTUFOQUdFUiIsImlhdCI6MTY4NTQ0NDIzMiwiZXhwIjoxNjg1NTMwNjMyfQ.06nL2Yz0ouMxryRmF4v3Sa737ejClDAC_AhnJiPO_sk

{
  "id": 1,
  "location": "서울시 강서구",
  "name": "코인 노래방",
  "storeInfo": "코노입니다.",
  "registrationNumber": "811-04-01601",
  "price": 10000
}

### 매장 삭제
DELETE http://localhost:9091/manager/store?id=2
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqbEhWc3JwZ2RxeW5RRUhVRkxtZ3lXdjVpako1M0tlb0dNZTVoa2lPc2RBPSIsImp0aSI6IlJucE8xSHd6NXo4WmhtWTZOUUphOVE9PSIsInJvbGVzIjoiTUFOQUdFUiIsImlhdCI6MTY4NTQ0MDcwNSwiZXhwIjoxNjg1NTI3MTA1fQ.aWaI6kpiJhqfcXtfg6SnK5BgROQQXwlZQoIyovJR0J8

### 매장 검색
GET http://localhost:9091/search/store?name=코인
Content-Type: application/json

